-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 30 avr. 2024 à 22:31
-- Version du serveur : 10.4.32-MariaDB
-- Version de PHP : 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `ecomerce`
--

-- --------------------------------------------------------

--
-- Structure de la table `product_table`
--

CREATE TABLE `product_table` (
  `id_prod` int(11) NOT NULL,
  `procduct_name` varchar(50) NOT NULL,
  `procduct_des` varchar(400) NOT NULL,
  `procduct_keyw` varchar(50) NOT NULL,
  `id_cat` varchar(4) NOT NULL,
  `procduct_image1` varchar(255) NOT NULL,
  `procduct_image2` varchar(255) NOT NULL,
  `procduct_image3` varchar(255) NOT NULL,
  `procduct_price` float NOT NULL,
  `date` timestamp(4) NOT NULL DEFAULT current_timestamp(4) ON UPDATE current_timestamp(4),
  `status` varchar(255) NOT NULL,
  `quan_stock` int(11) NOT NULL,
  `delivery_info` text DEFAULT NULL,
  `common_details` text DEFAULT NULL,
  `country` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `product_table`
--

INSERT INTO `product_table` (`id_prod`, `procduct_name`, `procduct_des`, `procduct_keyw`, `id_cat`, `procduct_image1`, `procduct_image2`, `procduct_image3`, `procduct_price`, `date`, `status`, `quan_stock`, `delivery_info`, `common_details`, `country`) VALUES
(21, 'Ribbed Glass Bottle Vases', 'These lovely ribbed glass bottle vases come in three different sizes, making them perfect for a variety of floral arrangements or decorative displays. Their elegant ribbed design adds texture and visual interest to any space.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Wedding-Table-Centrepiece-Decoration-Ideas-glass-bud-vases-bottles-1.webp', 'img1-2.webp', 'img1-4.webp', 145, '2024-04-03 17:08:43.1171', 'true', 50, 'Delivery throughout Morocco', 'These lovely ribbed glass bottle vases come in three sizes, making them ideal for accentuating floral arrangements at your wedding venue.\r\nWe recommend mixing and matching the sizes for the best effect. Use a group of 3-5 bottles per table as part of your centrepiece, and make sure they feature blooms in your wedding\'s colour palette.\r\nExtra small bottles measure 5.5cm x 10.5cm (height), small bottles measure 7.5 x 14cm (height), and large bottles measure 7.5 x 19cm (height), and all bottles are sold individually.', 'morocco'),
(22, 'Botanical Jar Vase', 'ovely botanical glass jar vases for wedding centerpieces or home décor. These charming glass jars feature a classic design with a botanical twist, perfect for adding a touch of natural elegance to any event or living space.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Botanical Jar Vase (3 Sizes) - Apothecary Style Wedding Vases.webp', 'img2-3.webp', 'img2-4.jpg', 150, '2024-04-03 17:09:19.1054', 'true', 45, 'Delivery throughout Morocco', 'Lovely botanical glass jar vases for wedding centrepieces & venue styling.\r\nAvailable in 3 sizes - we think they look best if you use both sizes together\r\nUse for accent flowers around your wedding venue\r\nUse a grouping of these vases as part of your centrepiece, we suggest 3 - 5 per table with flowers to match your wedding colour palette \r\nSizes\r\n\r\nsmall 7 x 14cm (height)\r\nmedium 8 x 16.5cm (height) \r\nlarge 10 x 20cm (height) ', 'morocco'),
(23, 'Bud Vase  Apothecary Style', 'Glass bud vases for wedding centerpieces & venue styling. These exquisite bud vases are the perfect choice for adding a touch of elegance to your special day. Crafted from high-quality glass, they boast a sleek and minimalist design that effortlessly complements any wedding theme or décor style.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Vintage Glass Bottle Vase with Gold Rim (2 Sizes) Wedding Centrepieces.webp', 'img3-4.webp', 'img3-5.webp', 100, '2024-04-03 17:10:05.7846', 'true', 33, 'Delivery throughout Morocco', 'Use for accent flowers around your wedding venue\r\nUse a grouping of these vases as part of your centrepiece, we suggest 3 - 5 per table with flowers to match your wedding colour palette.\r\n\r\nSizes:\r\n\r\nsmall 7 x 14cm (height)\r\nmedium 8 x 16.5cm (height) \r\nlarge 10 x 20cm (height)  \r\n', 'morocco'),
(24, 'Textured Pressed Glass Hurricane Vase', 'These textured pressed glass hurricane vases look stunning as standalone pieces or as part of a curated display. Their intricate patterns and elegant design add a touch of sophistication to any space, whether used as centerpieces for weddings, events, or simply as decorative accents in your home.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Textured Pressed Glass Hurricane Wedding Vase (3 Sizes).webp', 'img4-2.webp', 'img4-5.webp', 217, '2024-04-23 11:24:00.3958', 'true', 36, 'Delivery throughout Morocco', 'These textured pressed glass hurricane vases look lovely with flowers or candles.\r\nThese look stunning both inside and for decorating your outdoor spaces at your wedding venue.\r\n\r\nTry one larger vase as a centrepiece with a lovely bunch of fresh flowers, or for more impact on your tables place 4 of the smaller vases around the base with tealights or flowers inside. You could place these on a log slice or table runner for height and interest on your table.\r\n\r\nAvailable in 3 sizes:\r\n\r\nSmall : 7.5 (base) × 10.5 cm (Height) (use as a vase or tealight holder)\r\nMedium: 9.5 (base) x 13.5cm (Height)\r\nLarge: 12 (base) x 16 cm (Height)', 'morocco'),
(25, 'Dainty Clear Glass Bud Vases ', 'These dainty clear glass vases will make wonderful additions to any table setting or home décor arrangement. Their delicate design and transparent construction allow them to seamlessly blend with any style or theme, whether used for weddings, parties, or everyday decorating. Perfect for displaying single stems or small bouquets, these vases add a touch of charm and sophistication to any space.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Dainty Clear Glass Bud Vases Wedding Table Decorations - Set of 4.webp', 'img5-3.webp', 'img5-5.webp', 456, '2024-04-19 01:00:43.8143', 'true', 36, 'Delivery throughout Morocco', 'These dainty clear glass vases will make wonderful vases for your wedding tables.\r\nBud vases at weddings can be used as a group of 4 or 8 in the centre of a round table, for a rustic touch place them on a log slice.\r\nBud vases can be used on long trestle tables too, place them down the centre of the table and add a floral stem.\r\nBud vases can also be used as occasional vases for extra decoration to your guest book table, wedding cake table, cards and gift table.\r\nMade from clear glass\r\nSold as a set of 4, you will receive a mix of designs (not all vases in the set will be different).\r\n\r\nSize:\r\n\r\n10cm tall, narrow neck 1.5 - 2cm', 'morocco'),
(26, 'Blue Glass Bud Vases', 'A beautiful set of 3 cobalt blue glass vases. Perfect for adding a pop of vibrant color to your home decor or special events. These stunning vases feature an elegant cobalt blue hue that catches the light and adds a touch of sophistication to any space.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Blue Glass Bud Vases - Set of 3 Wedding Vases.webp', 'img6-2.webp', 'img6-4.webp', 256, '2024-04-23 14:44:51.7281', 'true', 31, 'Delivery throughout Morocco', 'A beautiful set of 3 cobolt blue glass vases. Perfect for adding a pop of colour to your wedding tables and venue.\r\n\r\nFinished with a cobalt blue glaze, the imperfect edges and bubbles in the glass add character and texture.\r\n\r\nApprox size L6.5 x W6.5 x H12 cm', 'morocco'),
(27, 'Amber Brown Glass Botanical Bottle Vase', 'Lovely amber, brown, and chestnut glass botanical glass vases, perfect for adding warmth and character to any space. These exquisite vases feature rich, earthy tones that evoke a sense of natural beauty and rustic charm.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Amber Brown Glass Botanical Bottle Vase (2 sizes) Wedding Centrepieces.webp', 'img7-3.webp', 'img7-4.webp', 207, '2024-04-03 17:13:02.5244', 'true', 26, 'Delivery throughout Morocco', 'Lovely amber, brown, chestnut glass botanical glass bottle vases for wedding centrepieces & venue styling.\r\nUse for accent flowers around your wedding venue\r\nUse a grouping of similar vases as part of your centrepiece, we suggest 3 - 5 per table with flowers to match your wedding colour palette.\r\nThey look great with our brushed gold candlesticks and french brown bottles.\r\nThe brown colour adds warmth and colour to your home or wedding venue. \r\nThese can be displayed empty, or add dried flowers or fresh flowers in them. \r\nGreat for Boho or Rustic styled weddings.\r\n\r\nSizes:\r\n\r\nSmall:   20cm (height) x 10cm (base) x 6.5cm (opening at top)\r\nLarge: 26cm (height) x 14cm (base) x 10cm (opening at top)', 'morocco'),
(28, 'Round Gold Rim & Glass Vases', 'Round clear glass and gold rim vases are the perfect combination of elegance and sophistication. These stunning vases feature a classic round shape with a delicate gold rim that adds a touch of glamour to any arrangement.', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'img8-2.webp', 'img8-3.webp', 'Set Of 2 Round Gold Rim & Glass Vases 8.5cm.webp', 130, '2024-04-03 17:13:34.8646', 'true', 29, 'Delivery throughout Morocco', 'Looking for small accent vases?\r\n\r\nOur round clear glass and gold rim vases are the perfect addition to guest book tables, ceremony tables, entrance tables, drinks stations, ladders or window sills, the list goes on.\r\n\r\nThey look great mixed in with other vases and bottles from our pressed glass or gold collection.\r\n\r\nThe round vases come in a set of 2 assorted. (see photos).\r\n\r\nSize: 8.5 x 8.5cm\r\n\r\nThese are the perfect fit for our dinner candles so you can also use them as candlesticks.\r\nPlease note these have been handmade by skilled artisans in India, the gold rims have been handpainted which may have slight imperfections which adds to their charm.', 'morocco'),
(29, 'Pink Glass Bud Vases', 'A beautiful set of 3 pale pink glass bottle vases, perfect for adding a soft and romantic touch to any space. These charming vases feature a delicate pale pink hue that exudes elegance and grace. ', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'Pink Glass Bud Vases - Set of 3.webp', 'img9-4.webp', 'img9-5.webp', 156, '2024-04-03 17:14:06.6605', 'true', 33, 'Delivery throughout Morocco', 'A beautiful set of 3 pale pink glass bottle vases. Perfect for adding a pop of colour to your wedding tables, tables in the bar area, next to your table plan, wedding cake or guest book.\r\n\r\nFinished with a pink glaze, the imperfect edges and bubbles in the glass add character and texture.\r\n\r\nOptions available:\r\n\r\nSet of 3 dimpled bottles: Size W6.3 x H10 cm\r\nSet of 3 assorted designs: Approx size L6.5 x W6.5 x H12 cm', 'morocco'),
(30, 'Pressed Glass Bottle Vases Amelie - Amber Brown', 'Pressed glass bottle vases in a warm amber color, reminiscent of the golden glow of autumn. These exquisite vases feature intricate pressed glass patterns that add texture and visual interest to any arrangement. ', 'bud,BUD VASE,wedding vase, bud vases,glass bottle ', '44', 'img10-2.webp', 'img10-3.webp', 'img10-4.webp', 199, '2024-04-23 14:44:51.7309', 'true', 14, 'Delivery throughout Morocco', 'We just love these pressed glass bottle vases in a warm amber colour. Perfect for adding to your wedding tables and around your venue. Mix and match these brown amber bottles with other amber vases in our collection.\r\n\r\nThe pretty etched bottles come in a set of 3 (assorted designs within each set).\r\n\r\nSize: approx 14cm x 6cm (base)', 'morocco'),
(32, 'mason pot vase in silver metal', '2 Mason jar vases in silver metal. The jars are quaint and charming, perfect for adding a touch of rustic elegance to any space. Each jar features a silver metal lid and band, adding a subtle metallic accent to the classic Mason jar design. ', 'decoration,mason jar,flowers,pens,silver metal,han', '46', '2 Vases Mason Jar - Métallisé Argent.jpg', 'img2-2.jpg', 'img2-2.jpg', 200, '2024-04-03 17:17:24.1860', 'true', 20, 'Delivery throughout Morocco', 'Details of the article:\r\nHandmade\r\n2 mason pot vase in silver metal.\r\nThe jars are quarter-sized (32 oz) regular mouth.', 'morocco'),
(33, 'Mason jar vase quarter size', 'Mason jar vase for any occasion or decor for your home. This versatile vase combines rustic charm with timeless elegance, making it a perfect addition to any setting. ', 'decoration,mason jar,flowers,pens,quarter size,wid', '46', 'Mason Jar Vase.webp', 'img3-2.webp', 'img3-2.webp', 110, '2024-04-03 17:18:19.8640', 'true', 25, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nBeautiful Mason jar vase for any occasion or decor for your home.\r\n\r\nThe jar is quarter size with a wide mouth top. Variety of colors available.\r\nThe pot is in distress for a rustic look and the paint is sealed.\r\n\r\nLarge quantity order please message me to discuss prices.', 'morocco'),
(34, 'Decorative mason jar', 'Lovely Mason jar vase for any occasion or decor for your home. This charming vase blends rustic allure with timeless elegance, making it an ideal addition to any setting. ', 'decoration,mason jar,flowers,pens,holder', '46', 'Pot Mason décoratif.jpg', 'img4-2.jpg', 'img4-2.jpg', 112, '2024-04-03 17:19:03.5026', 'true', 29, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nDecorative mason jar\r\nMulti-purpose. Can be used as pencil holder, flower vase and more.', 'morocco'),
(36, 'Dentelle mason jar vase', 'Mason Jar glass jar adorned with lace enhances your decor with vintage charm and romantic appeal. ', 'decoration,mason jar,flowers,pens,mariage,wedding', '46', 'bocal en verre façon Mason Jar.avif', 'img6-2.avif', 'img6-2.avif', 50, '2024-04-03 17:19:43.4812', 'true', 36, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: Lace\r\n\r\nThis Mason Jar glass jar adorned with lace enhances your party decoration. This wedding vase is original, it will give a country side to your decoration center wedding table. , wedding or baptism. The jar is about 12 cm high.', 'morocco'),
(37, 'Glass mason jar', 'A standard size Mason jar ring will be securely glued to each jar, adding a touch of rustic charm to your decor. ', 'decoration,mason jar,flowers,pens,flower frogs', '46', 'Grenouille fleur en céramique.avif', 'img7-2.jpg', 'Grenouille fleur en céramique.avif', 180, '2024-04-03 17:20:24.3121', 'true', 21, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nRead the full description\r\nMaterials: Mason jar, green vegetables, flowers, glaze, clay, pottery, ceramics\r\n\r\n\r\nThese flower frogs are designed to garnish a mason jar, a variety of vases and cups or glasses.\r\nThey are perfect when you only have a few flowers but want them to stay tall.\r\n\r\nA standard size mason jar ring will be glued to each of them. This allows them to be screwed into a Mason jar or attach them to the top of most vase openings and they also fit perfectly inside a large jar with mouthpiece.\r\n\r\n* Also works wonders for plant propagation 🌱.\r\n\r\n** The \"Big Flower\" is about 4.5 inches in diameter and can easily cover a large, wide-open can jar or anything smaller than 4 inches in diameter.\r\n\r\n** \"Round\" package measures about 3.75 in. round - can also cover a large jar with a smaller mouthpiece\r\n\r\n** the \"small flower\" measures 3.5 inches in diameter, ideal for regular mason jars and other smaller neck vases.\r\n\r\nAll ceramic pieces are baked into biscuit, then glazed and baked again, making them safe for indoor and outdoor use. I do not recommend leaving it outside/unprotected in winter - freezing and thawing could crack parts.', 'morocco'),
(38, 'shabby chic mason jar', 'This listing is for a very shabby chic and chic painted Mason jar centerpiece. Each Mason jar is meticulously hand-painted with a shabby chic finish, adding a touch of vintage-inspired elegance to your decor. ', 'decoration,mason jar,flowers,pens,lilac color', '46', 'Pot Mason peint shabby chic.avif', 'img8-2.avif', 'img8-2.avif', 150, '2024-04-03 17:20:56.1317', 'true', 17, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\n\r\nThis listing is for a very shabby chic and chic painted mason jar with string and a small flower, as shown in the third picture of the white jar. Choose your or your colors. Each jar has been painted, aged and sealed. The flowers at the top and bottom are only photo accessories and are not included. The pots in the first photo are larger and measure 6-1/2 inches. The latest photos are provided as a sample. The lilac color of the last photo is represented with 3 tiny pink buttons at the top. You will receive your Choice of Color in the largest Mason jar the size of a quarter of a liter, standard opening or large opening.', 'morocco'),
(40, 'Vintage glass bottles', 'Two vintage glass bottles have been repurposed from their original use in medicine, adding a nostalgic touch to your decor. ', 'decoration,flowers,narrow neck vases,glass', '47', 'transparent narrow neck vase.avif', 'img1-2.avif', 'img1-2.avif', 190, '2024-04-23 11:24:00.3994', 'true', 36, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nVintage 1970s\r\nMaterials: glass\r\n\r\n\r\nThis set of 2 vintage glass bottles has been used in medicine, perfumery or chemistry laboratories. You can now use this clear glass container to decorate your home and kitchen. This small vase could be your table decoration. This narrow neck collection bottle is perfect for photo projects.\r\n\r\nsizes:\r\nheight 18 cm (7\")\r\nBottom diameter 4.5 cm (1.8\")', 'morocco'),
(41, 'Vintage narrow neck vase', 'Glass narrow-neck vases for venue styling offer a sleek and sophisticated option for your event decor. ', 'decoration,flowers,glass,vintage', '47', 'img2-1.avif', 'img2-2.avif', 'img2-3.avif', 20, '2024-04-03 17:22:39.9318', 'true', 12, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nVintage 1990s\r\nThe vase measures 16 inches (almost 41 cm).\r\n\r\nHas a bluish green hue when the background is white.', 'morocco'),
(42, 'Stella glass vase', 'The Stella vase plays beautifully with the light in your space, casting enchanting reflections and creating a mesmerizing ambiance.', 'decoration,flowers,narrow neck vases,glass,stella', '47', 'img3-1.avif', 'img3-2.avif', 'img3-1.avif', 600, '2024-04-03 17:23:29.4707', 'true', 22, 'Delivery throughout Morocco', 'Détails de l’article :\r\n\r\nFait main\r\nMatériaux : Plastique PLA végétal\r\n\r\nLargeur : 15.7 cm\r\nProfondeur : 15.7 cm\r\nEmballage cadeau possible\r\nDonnez à votre espace une touche élégante avec le vase de sol STELLA.\r\n\r\nSTELLA est un accroche-regard qui transforme n’importe quel coin vide en un endroit chaleureux et confortable. Le style de vie minimaliste a inspiré le design du vase. Les lignes épurées et la forme fluide donnent au vase un aspect doux et naturel qui est parfait pour un intérieur moderne.\r\n\r\nWith its striped texture, the vase plays beautifully with the light in your space. Its appearance seems to change when you look at it from different angles. The floor vase is available in five shades: black, white, anthracite, beige and green. So you will effortlessly find the vase that suits your style. Place the vase next to your favorite decoration, or style with colorful dried flowers for a unique touch in your home.\r\n\r\nGive your interior a boost with the STELLA 3D printed floor vase!\r\n\r\nAn eye-catcher that makes your home shine.\r\nThe flowing shape of STELLA creates a playful reflection of light in your space. This makes the vase a real eye-catcher that makes your interior shine.\r\n\r\nA personal touch for your interior.\r\nThis 3D printed vase is robust yet lightweight. This makes it easy to move and gives your interior a unique and personal touch. The vase is built up layer by layer, so you can see how it is made.\r\n\r\nStylish and sustainable.\r\nThe vase is made of renewable bio-plastic based on corn starch. This makes the vase stylish and eco-friendly.\r\n\r\nNOTE: The vase is not suitable for water.\r\n\r\nDimensions: 15.7 x 50 cm\r\nNeck diameter: 5.1 cm\r\nWeight: 461 grams\r\n\r\nDimensions: 17.2 x 55 cm\r\nNeck diameter: 5.6 cm\r\nWeight: 558 grams\r\n\r\nDimensions: 18.8 x 60 cm\r\nNeck diameter: 6.1 cm\r\nWeight: 666 grams\r\n', 'morocco'),
(46, 'Decorative vase with long collar', 'A vase with a long collar is a decorative vase that adds a touch of elegance and sophistication to any space.', 'decoration,flowers,narrow neck vases,volume, porce', '47', 'img7-2.jpg', 'img7-1.jpg', 'img7-2.jpg', 160, '2024-04-03 17:24:18.5064', 'true', 34, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: volume, porcelain, glass, earthenware\r\n\r\nWidth: 9.5 centimeters\r\nHeight: 19.5 centimeters\r\nThis vase with long collar is a decorative vase. The neck is quite narrow about 0.7 cm in diameter, so it is only suitable for herbs, branches or flowers of long-stemmed fields.\r\nIt has a green glaze, which is replaced on one side by a transparent glaze.', 'morocco'),
(48, 'Black handmade urn vase', 'A medium-sized handmade vase in black with a subtle sheen is a striking addition to any decor. Crafted with care and attention to detail, this vase boasts a sleek and modern design that effortlessly enhances any space.', 'decoration,flowers,urn vases,ceramic, clay', '48', 'img1-1.avif', 'img1-1.avif', 'img1-1.avif', 640, '2024-04-03 17:25:05.9779', 'true', 44, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: ceramic, clay\r\n\r\nWidth: 5 inches\r\nHeight: 5 inches\r\nDepth: 5 inches\r\nThis medium-sized handmade vase is black with a subtle electric blue stain. This vase will be ideal for decorating flowers and will complement any modern decor.', 'morocco'),
(49, 'Crystal-clear jar', 'A crystal-clear jar, meticulously crafted by us in our home studio, embodies artisanal excellence and attention to detail. Each jar is lovingly handmade, ensuring the highest quality and a one-of-a-kind aesthetic. ', 'decoration,flowers,urn vases,argile, glaçage, porc', '48', 'img2-1.webp', 'img2-2.avif', 'img2-1.webp', 1520, '2024-04-19 01:30:32.8171', 'true', 7, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nRead the full description\r\nMaterials: clay, glaze, porcelain, heat, fire\r\n\r\nThis crystal-clear jar was made by us in our home studio. All our pieces are thrown by hand on the potter’s wheel. No two parts are exactly the same in form, and crystal formations can never be duplicated. Therefore, each piece is truly one of a kind.\r\n\r\nThis piece measures 8 1/4\" high to the top of the lid by about 4 3/4\" wide at its widest point. The pot is only 6 7/8\" tall. It weighs 1 lb 15 oz. A foot ring was cut underneath and then ground flat for a smooth finish.\r\n\r\nWe used a smooth white porcelain stoneware for this piece. It was heated to 2345 degrees Fahrenheit (high fire cone 10) and cooled in a specific process to grow crystals.\r\n\r\nCrystalline enamels are different from most enamels in that the pattern you see on them is created from zinc silicate crystals, similar to the natural mineral called willemite. These crystals grow literally in the glaze, but only with special attention to the application of the glaze, the composition of the glaze and a very controlled cooking process.\r\n\r\nEach piece is waterproof, microwave and dishwasher safe, lead free and the colors do not fade.\r\n', 'morocco'),
(50, 'Colored antique rustic style ceramic vase', 'This vase is perfect for dried flowers or artificial arrangements, providing a stunning showcase for your decorative creations. Its crystal-clear design allows the intricate details and textures of dried flowers or artificial stems to shine, creating a captivating display that adds beauty and charm to any room. ', 'decoration,flowers,urn vases,ceramic', '48', 'img3-1.webp', 'img3-2.avif', 'img3-1.webp', 580, '2024-04-03 17:26:46.6603', 'true', 27, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: Ceramic\r\n\r\nWidth: 17 centimeters\r\nHeight: 16 centimeters\r\nDepth: 17 centimeters\r\nColour - stone\r\nThe aperture measures 9 wide cams\r\nThis eye-catching stone-colored antique rustic style ceramic vase is a perfect complement to your relaxing country style interior. Perfect for any window sill, dining table, side table, coffee table, console table, etc.', 'morocco'),
(54, 'Hand painted urn jar', 'An urn vase for any occasion or decor for your home is a versatile and timeless addition to your interior design.', 'decoration,flowers,urn vases,Lid vase, Urn,Jar , p', '48', 'img7-1.webp', 'img7-2.avif', 'img7-1.webp', 400, '2024-04-03 17:27:23.7646', 'true', 37, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nVintage 1960s\r\nLid vase/ Urn/ Jar - porcelain - flower decor - vintage - hand painted\r\nThe vase is in good condition.\r\nThe size is 21 x 12 cm (8.3 x 4.7 inches)\r\n\r\nThe photos are part of the description.\r\nThe products will be carefully packed and shipped insured with tracking and traceability.', 'morocco'),
(56, 'Mason jar vase-black and white floral pattern.', 'Classy urn vase for any occasion or decor for your home, exuding timeless elegance and sophistication.', 'decoration,flowers,urn vases,glass,painted', '46', 'Découpage Mason Jar.avif', 'img5-2.avif', 'Découpage Mason Jar.avif', 230, '2024-04-23 14:44:51.7331', 'true', 37, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nGift wrapping possible\r\nHandmade 32 oz Mason jar vase, black and white floral pattern.\r\n\r\nSealed for extra protection but not dishwasher safe.\r\n\r\nFloral NOT included', 'morocco'),
(66, 'Hand-made black urn with gold leaf', 'Hand-made black urn with gold leaf accents, exuding elegance and sophistication. Each urn is meticulously crafted by hand, ensuring unique character and attention to detail.', 'decoration,flowers,urn vases,clay, glaze', '48', 'img4-1.avif', 'img4-2.jpg', 'img4-1.avif', 1580, '2024-04-03 17:29:44.6822', 'true', 50, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: clay, glaze, black glaze, black slip, sandstone, gold alloy sheet, gold sizing\r\n\r\nWidth: 3.5 inches\r\nHeight: 6.5 inches\r\nDepth: 3.5 inches\r\nHand-made black urn with gold leaf. Thrown at the wheel, covered with a black slip, then glazed with glossy black. Meticulously hand-crafted hardwood accents with a gold alloy. Will retain water, if used as a flower vase, or will serve as a beautiful memorial to a deceased family member or pet.\r\n\r\nStamped, initialed and dated by scribbling through the brief on the bottom so that the original white of the stoneware appears through.\r\n\r\nDimensions: 6.5\" tall by 3.5\" wide. Weighs just over 14.2 oz.', 'morocco'),
(68, 'Antique funerary vase ', 'Antique funerary vase in natural stone marble, exuding timeless beauty and historical significance. ', 'decoration,flowers,urn vases,Antique funerary ', '48', 'img6-1.avif', 'img6-2.avif', 'img6-1.avif', 500, '2024-04-03 17:30:44.3441', 'true', 49, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nAntique funerary vase in natural stone marble H 20,2 cm\r\nUnfortunately, the manufacturer’s brand cannot be deciphered.\r\n \r\nSize: H 20.2 cm | D 7.2 cm\r\nCondition:\r\nThe item is in good condition (see photos), it has slight traces of wear.\r\nThere are deposits or limestone inside.\r\nVery good = new or like new/collectible good = unsatisfactory little used item = frequently used enough = very used bad = very used amateur object = defective.', 'morocco'),
(71, 'Large white modern vase', 'The ceramic clay formulation is of fairly high quality, ensuring durability, strength, and a smooth finish. ', 'decoration,flowers,narrow neck vases,ceramic', '47', 'img8-1.avif', 'img8-3.avif', 'img8-2.avif', 999, '2024-04-03 17:33:18.0070', 'true', 47, 'Delivery throughout Morocco', 'Details of the article:\r\n\r\nHandmade\r\nMaterials: ceramic\r\n\r\nWidth: 9 centimeters\r\nHeight: 39 centimeters\r\nDepth: 3 centimeters\r\nLarge white modern vase\r\n\r\nHeight: 39 cm\r\nTop diameter and bottom diameter: 3 cm, 9 cm\r\n\r\nOur ceramic clay formulation is of fairly high quality, thanks to our 20 years of experience in the ceramic industry. It consists of feldspar, quartz, kaolinite, sodium silicate\r\nBefore starting production, we work in depth on design and modeling. Our production processes are as follows: molding, retouching, pre-drying, retouching, baking the biscuit at 1000-1050 C (in order to have a homogeneous color structure), color selection, priming and glazing by dipping, oven drying at 1100 C.', 'morocco'),
(92, ' Deco Vase White', 'Our art vase provides a warm and quaint atmosphere', 'ceramic CERAMIC vase VASE ', '50', 'E.webp', 'EE.webp', 'E.webp', 299, '2024-04-02 22:44:18.0000', 'true', 50, 'Delivery throughout Morocco', 'Irregular designs are elegant and dignified. Exquisite workmanship, novel design, and vivid sculpture. Pure hand-made products, simple and unique style.  Material: Ceramic & Porcelain Function: Tabletop Vase Art vases: miniature model', 'morocco'),
(93, 'GUGGENHEIM Long-necked ceramic vases', 'With elegant lines, refined texture and modern sty', 'vase ceramic CERAMIC GUGGENHEIM ', '50', 'H.webp', 'HH.webp', 'HHH.webp', 700, '2024-04-02 22:49:00.0000', 'true', 20, 'Delivery throughout Morocco', 'With elegant lines, refined texture and modern style, GUGGENHEIM vases are one of the most loved items of The Trophy Wife. Available in 5 different shapes and sizes.  Beautiful on their own, extremely spectacular when combined with each other.', 'morocco'),
(94, 'VASE MODERNE EN CÉRAMIQUE', 'Modern ceramic vases blend the traditional art of pottery with contemporary design aesthetics.', 'ceramic CERAMIC vase VASE ', '50', 'B.webp', 'BB.webp', 'BBB.webp', 800, '2024-04-19 01:08:43.8396', 'true', 26, 'Delivery throughout Morocco', 'This modern ceramic vase is ideal for apartments. Its intricate shape makes it authentic and pleasing to look at. Material: ceramic Size: available in 3 different sizes.', 'morocco'),
(95, 'Pastille vase ', 'The Pastill vase is a beautiful and stylish interior piece.', 'ceramic CERAMIC vase VASE ', '50', 'D.webp', 'DDD.webp', 'DD.webp', 250, '2024-04-19 01:00:43.8168', 'true', 13, 'Delivery throughout Morocco', 'The Pastill vase from Cooee Design is a stunning piece that adds elegance and style to any interior setting. Crafted by the renowned Swedish brand, known for its exceptional craftsmanship and contemporary designs, this vase is a true standout.', 'morocco'),
(96, 'Modern Ceramic Vase with Glass Test Tube: Unique W', 'Modern white ceramic vase with glass test tube ', 'ceramic CERAMIC vase VASE ', '50', 'LLL.jpg', 'LL.jpg', 'LLLL.jpg', 450, '2024-04-19 01:23:45.0352', 'true', 28, 'Delivery throughout Morocco', 'Stylish and practical, this modern white ceramic vase features a unique chain-like design with a glass test tube, blending seamlessly into various home decor styles. Crafted from high-quality materials, including ceramic and borosilicate glass, it is durable and easy to maintain. Perfect for displaying flowers or hydroponic plants, this versatile vase adds a touch of elegance to any room and makes a thoughtful gift for any occasion.', 'morocco'),
(97, 'Handmade Ceramic Vase Set', 'Enhance your home decor with this exquisite handmade ceramic vase set, featuring a contemporary and stylish design. Crafted by skilled artisans, these vases are perfect for adding a touch of modern elegance to any room.\r\n\r\n\r\n\r\n\r\n\r\n', 'ceramic CERAMIC vase VASE ', '50', 'J.webp', 'JJ.webp', 'JJJ.webp', 700, '2024-04-03 17:08:40.2978', 'true', 40, 'Delivery throughout Morocco', 'Material: Made from high-quality ceramic, ensuring durability and a stylish appearance.\r\nDimensions: Typically available in various sizes to suit different preferences and spaces.\r\nColors: Offered in a range of colors and finishes, allowing for versatile decor matching.\r\nUsage: Suitable for displaying artificial or fresh flowers, enhancing the aesthetic of living spaces.\r\nMaintenance: Easy to clean and maintain, requiring simple care to preserve their beauty over time.\r\nStyle: Featuring unique designs that add character and charm to any room, fitting various decor styles.', 'morocco'),
(98, 'Hand-Painted Matte Ceramic Ball Vase', '\r\nHandmade ceramic vase set blending artisanal elegance with modern design and functional versatility. ', 'ceramic CERAMIC vase VASE HAND BALL ball', '50', 'P.webp', 'OOO.webp', 'OO.webp', 600, '2024-04-03 17:10:49.3736', 'true', 34, 'Delivery throughout Morocco', 'The hand-painted matte ceramic ball vase is a versatile and elegant decor piece. Its petite size and round shape make it perfect for displaying botanical arrangements or standing alone as a statement item. The matte finish adds a touch of sophistication, while the hand-painted details ensure each vase is unique. Its versatility allows it to fit seamlessly into various decor styles, making it a charming addition to any space.', 'morocco'),
(99, 'Shades of Blue Ceramic Vase ', 'Hand-painted ceramic vases in calming blue hues, perfect for showcasing flowers or adding a serene touch to your decor.', 'ceramic CERAMIC vase VASE BLUE blue', '50', 'kkkk.jpg', 'KK.webp', 'KKK.webp', 1200, '2024-04-03 17:12:22.7032', 'true', 34, 'Delivery throughout Morocco', 'This timeless ceramic vase set features a soft palette of blue, beige, and jade, creating a breezy, summery vibe that lasts all year round. Hand-painted and crafted from non-porous, water-resistant ceramic and porcelain materials, these tabletop vases come in 6 relaxing shades of blue, adding a calm and serene ambiance to any table setting. Whether showcasing your favorite flowers or serving as a room accent, these vases are a perfect addition to your decor.', 'morocco'),
(100, 'Minimalist White Ceramic Flower Vase', 'Blending modern style with artistic flair, the BUICCE vase is a versatile and fashionable piece, perfect for housewarming or wedding gifts. ', 'ceramic CERAMIC vase VASE ', '50', 'AAAA.jpg', 'AAA.jpg', 'A1.jpg', 1000, '2024-04-03 17:15:06.3538', 'true', 15, 'Delivery throughout Morocco', 'The modern style and fashionable appearance of the BUICCE vase make it the perfect gift for housewarming or weddings. Its safe packaging ensures that it will arrive at your doorstep in pristine condition.', 'morocco'),
(101, 'Wooden Test Tube Vase', 'A wooden test tube vase is a stylish and minimalis', 'wodeenvase WODEEn vase tube ', '45', '1.webp', '11.webp', '111.webp', 1500, '2024-04-03 01:17:11.0000', 'true', 30, 'Delivery throughout Morocco', 'A wooden test tube vase is a small, minimalist home decor item made of wood and typically designed to hold one or a few test tubes for displaying small flowers or greenery. Its natural aesthetic and minimalist design make it a versatile and space-saving addition to any room, adding warmth and organic beauty to your decor.', 'morocco'),
(102, 'Geometric Rustic Wooden Vases', 'Geometric Rustic Wooden Vases: Unique and charming', 'WOODEN VASES vase rustic RUSTIC', '45', '2.avif', '22.avif', '222.avif', 249, '2024-04-03 01:28:05.0000', 'true', 30, 'Delivery throughout Morocco', 'A wooden test tube vase is a stylish and minimalist home decor item made from high-quality wood. It features slots or holes to hold one or more glass test tubes, perfect for displaying small flowers or greenery. Its natural aesthetic, versatility, and compact size make it an ideal choice for enhancing any room\'s decor.', 'morocco'),
(103, 'Melanie Abrantes Walnut Hardwood Vase', ': A sleek and minimalist wooden vase from Melanie ', 'WOODEN VASES vase MELANIE', '45', '333.jpg', '3.jpg', '33.jpg', 600, '2024-04-03 01:45:42.0000', 'true', 40, 'Delivery throughout Morocco', 'The Melanie Abrantes Walnut Hardwood Vase is a beautifully crafted home decor piece made of high-quality walnut wood. Its compact and minimalist design is perfect for displaying a single stem or a small bouquet of flowers, adding a natural and elegant touch to any room. The vase\'s smooth finish and expert craftsmanship exemplify Melanie Abrantes\' attention to detail, making it not just a functional item but also a statement art piece that enhances your interior decor.', 'morocco'),
(104, 'Melanie Abrantes Tall Hardwood Vase', 'Upgrade your decor with the Melanie Abrantes Tall ', 'WOODEN VASES vase MELANIE TALL', '45', '555.jpg', '5.jpg', '55.jpg', 240, '2024-04-03 02:03:19.0000', 'true', 10, 'Delivery throughout Morocco', 'Crafted from premium hardwood with a smooth natural wood grain finish, the Melanie Abrantes Tall Hardwood Vase exudes modern minimalist style. Ideal for showcasing tall flowers, branches, or dried arrangements, this handcrafted vase adds sophistication to any space. With easy maintenance and versatile placement options in living rooms, dining areas, or offices, it\'s also a perfect gift choice. Each vase is uniquely handcrafted, guaranteeing quality craftsmanship and timeless elegance', 'morocco'),
(105, ' Sculpted and Semi-Burnt Wooden Vase', 'Discover the allure of our Sculpted and Semi-Burnt', 'WOODEN VASES vase SCUPTED Scupted', '45', '6.webp', '7.webp', '6.webp', 250, '2024-04-03 16:52:16.9636', 'true', 50, 'Delivery throughout Morocco', '\r\nMaterial: High-quality wood\r\nTechnique: Sculpted and semi-burnt for a distinctive look\r\nStyle: Rustic, artistic\r\nPurpose: Ideal for showcasing flowers or as a standalone decorative piece\r\nDimensions: Length: 30 cm, Width: 20 cm, Height: 15 cm\r\nCare: Wipe with a soft cloth; avoid direct sunlight and moisture exposure\r\nOne Review: \"A wonderful artistic piece, adds a charming atmosphere to the space.\" (One-star rating)', 'morocco'),
(106, 'Outback Hills Wooden Vase', ' Explore the beauty of our Outback Hills vase, a d', 'wodeenvase WODEEn vase OUTBACK outback', '45', '20.webp', '30.webp', '10.webp', 1250, '2024-04-28 22:26:27.3051', 'true', 9, 'Delivery throughout Morocco', 'This is our Outback hills vase , a very special and unique piece of home decor  that you can play around with to display in a variety of positions. This versatile vase has 3 glass test tubes so you can display anything  from dry to fresh flowers or even propagate your favourite plants!\r\nMade of :\r\n- Australian reclaimed pine timber\r\n- Glass test tubes.', 'morocco'),
(107, 'Handmade Wooden Test Tube Vase', 'Add a unique touch to your decor with our handmade', 'WOODEN VASES vase HANDMADE TUBE handmate tube', '45', 'M.webp', 'MMM.avif', 'MMM.avif', 290, '2024-04-19 01:08:17.7545', 'true', 32, 'Delivery throughout Morocco', 'Material: High-quality wood\r\nStyle: Geometric, minimalist\r\nUse: Home decoration, propagation station', 'morocco'),
(108, 'Minimalist Geometric Wooden Flower Vase', 'Elevate your space with our handcrafted wooden flo', 'WOODEN VASES vase Geometric minimalist ', '45', 'YYY.avif', 'Y.jpg', 'YY.avif', 750, '2024-04-19 01:00:43.8185', 'true', 21, 'Delivery throughout Morocco', 'Material: High-quality wood\r\nStyle: Geometric, minimalist\r\nUse: Home decoration, fresh flower display\r\nDimensions: Length: 25 cm, Width: 25 cm, Height: 10 cm\r\nCare: Wipe with a soft cloth; avoid direct sunlight and moisture exposure\r\n\r\n\r\n\r\n\r\n\r\n', 'morocco'),
(109, 'Dried Flower Bouquet with Vase and Fairy Lights', ' delicate and tender dried flower bouquet perfect ', ' Fairy Lights light-up vase ', '49', 'LUMIN.jpg', 'LUMIN.jpg', 'LUMIN.jpg', 150, '2024-04-03 16:56:48.9363', 'true', 40, 'Delivery throughout Morocco', 'Dried flower bouquet, vase, gravel, fairy lights\r\nDimensions: Approximately 22cm (tallest) x 10cm (widest) when displayed in the vase\r\nShipping: Carefully packaged for safe delivery\r\nDelivery Options: Hand delivery available in Rochefort; free delivery in Rochefort (select \"hand delivery\" and contact seller)\r\nStyle: Soft, bohemian\r\nPerfect for: Light and airy decor, bohemian-inspired settings\r\n\r\n\r\n\r\n\r\n\r\n', 'morocco'),
(110, 'Rose Mini Lighted Bud Vase', 'Elevate your event with our Rose Mini Lighted Bud ', 'vase ceramic  Mini Lighted', '49', '78.webp', '78.webp', '78.webp', 400, '2024-04-03 04:08:42.0000', 'true', 54, 'Delivery throughout Morocco', 'Material: High-quality materials\r\nSize: Miniature size, perfect for table settings\r\nLighting: Features built-in LED lights for a soft glow\r\nUsage: Ideal for weddings, showers, parties, and special events\r\nStyle: Elegant and charming\r\nPackaging: Carefully packaged for safe delivery\r\nShipping: Worldwide shipping available, contact us for details\r\nCustomization: Option available for custom colors or arrangements\r\nPrice: Competitive pricing, inquire for bulk orders or special requests', 'morocco'),
(111, 'Subtle Glow with Candles and Lighting', 'Enhance your ambiance affordably with candles, cre', 'Subtle VASE vase Lighting', '49', '90.jpg', '90.jpg', '90.jpg', 300, '2024-04-03 04:13:54.0000', 'true', 20, 'Delivery throughout Morocco', 'Affordable solution for ambiance: Candles provide a cost-effective way to create a warm glow.\r\nAdditional lighting options: Consider colored washes, uplighting, or pin spotting for enhanced ambiance.\r\nBudget considerations: Choose options that align with your budget and desired aesthetic.\r\nVersatile decor: Candles and lighting can be tailored to suit various themes and atmospheres.\r\nPersonalized touch: Customize lighting choices to achieve your desired ambiance and mood.', 'morocco'),
(112, 'Flower Vase Lamp', 'Illuminate your space with elegance using our Flow', 'vase light-up vase lampe ', '49', 'PP.jpeg', 'PP.jpeg', 'PP.jpeg', 600, '2024-04-03 15:56:41.0000', 'true', 40, 'Delivery throughout Morocco', 'Material: High-quality materials\r\nDesign: Combines a vase and lamp into one stylish piece\r\nFunctionality: Use as a vase to display flowers or as a lamp for soft, ambient lighting\r\nStyle: Elegant and functional\r\nIdeal for: Adding a touch of sophistication to any room or event\r\nLimited time offer: Get yours now at a discounted price!\r\n\r\n\r\n\r\n\r\n', 'morocco'),
(113, 'Farmhouse Green Tint Glass Vase with Fairy Lights', 'Discover our Farmhouse Green Tint Glass Vase with ', 'VASE vase LIGHT ligth green fairy FAIRY', '49', 'PL.avif', 'PLL.jpg', 'PL.avif', 200, '2024-04-03 16:21:05.0000', 'true', 30, 'Delivery throughout Morocco', 'Handcrafted green tint glass vase for farmhouse decor\r\nComes with artificial flowers and fairy lights\r\nFlowers can be easily switched for a new look\r\nJar height: 12 inches; with flowers: approximately 28 inches\r\nJar diameter: 7 inches\r\nFairy lights have a timer (6 hours on, 18 hours off) and 3 lighting modes\r\nBattery included for fairy lights\r\nAdds rustic charm and ambiance to any space', 'morocco'),
(114, 'Colorful LED Glass Dome Flower Rose', 'Illuminate your space with our Colorful LED Glass ', 'Colorful LED Colorful LED Glass Dome Flower Rose V', '49', 'FIN.jpg', 'FIN2.jpg', 'FIN3.jpg', 500, '2024-04-19 01:08:17.7563', 'true', 11, 'Delivery throughout Morocco', 'Compact LED lights embedded in the flower petals\r\nBottom switch for easy on/off control\r\nCreates a colorful and mesmerizing light display\r\nSuitable for decorating rooms or creating a romantic atmosphere\r\nCan be used as a night light in a child\'s bedroom\r\nSolid wood base for durability and stability\r\nPerfect for Christmas, Valentine\'s Day, Mother\'s Day, birthdays, or as a thoughtful gift', 'morocco');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `product_table`
--
ALTER TABLE `product_table`
  ADD PRIMARY KEY (`id_prod`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `product_table`
--
ALTER TABLE `product_table`
  MODIFY `id_prod` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=121;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
